### PR TITLE
fix `nextPageToken` argument with missing `display` argument

### PR DESCRIPTION
**Pull request by oshliaer**
I have more than 100 files on my Drive =)

### CODE REVIEW

**Comment by oshliaer** [comment]
It's a complex trouble.

**Comment by MaartenDesnouck** [comment]
Ow, thats not good. Ill have a fixed version published in 12hours. (In the mean time any easy fix is to change the pagesize from 100 to the max value of 1000)

**Comment by MaartenDesnouck** [comment]
@oshliaer Want to do 'npm i -g google-apps-script' and get back to me if the bug has been fixed?

**Comment by oshliaer** [comment]
@MaartenDesnouck Of course!
I found another similar problem elsewhere. But I'm not sure that I'm right about how to solve it.

**Pull request closed without merging**
